# Generated by Django 5.1.6 on 2025-02-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_driving', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_on_duty', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_off_duty', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_sleeper_berth', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('events', models.JSONField(blank=True, default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trip.trip')),
            ],
        ),
    ]
