# Generated by Django 5.1.6 on 2025-02-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='geometry',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
